/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hanafuda;

import java.awt.*;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

public class AppScreen extends javax.swing.JFrame {
    
    private static final int X_DIMEN = 960;
    private static final int Y_DIMEN = 540;
    private static final javax.swing.JPanel[] screens = new javax.swing.JPanel[5];
    //0: HomeScreenBgrd
    //1: HomeScreen
    //2: HTPScreen
    //3: GameBgrd
    //4: GameScreen
    
    public AppScreen() throws FileNotFoundException {
        initComponents();
        initializeScreens();
        this.setSize(975, 580);
        JLayeredPane home = new JLayeredPane();
        home.add(screens[0], 1);
        home.add(screens[1], 2);
        home.add(screens[2], 2);
        this.add(home);
        home.setSize(960, 540);
        JLayeredPane game = new JLayeredPane();
        game.add(screens[3],1);
        game.add(screens[4], 2);
        this.add(game);
        showScreen("home", home);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AppScreen().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(AppScreen.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    public void initializeScreens() throws FileNotFoundException {
        screens[0] = new HomeScreenBgrd();
        screens[1] = new HomeScreen();
        screens[2] = new HTPScreen();
        screens[3] = new GameBgrd();
        screens[4] = new GameScreen();
        for (int i = 0; i < screens.length; i++) {
            screens[i].setLocation(0, 0);
            screens[i].setSize(X_DIMEN, Y_DIMEN);
            screens[i].setVisible(false);
            screens[i].setOpaque(false);
        }
    }
    
    public void showScreen(String screenName, javax.swing.JLayeredPane lp) {
        //0: HomeScreenBgrd
        //1: HomeScreen
        //2: HTPScreen
        //3: GameBgrd
        //4: GameScreen
        switch(screenName) {
            case "home":
                lp.setVisible(true);
                lp.moveToFront(screens[0]);
                lp.moveToFront(screens[1]);
            case "htp":
                lp.setVisible(true);
                lp.moveToFront(screens[2]);
            case "game":
                
            case "highScore":
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
