/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hanafuda;

import java.awt.*;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JFrame;

public class HomeScreen extends javax.swing.JPanel {

    private static AppScreen parent;
    
    public HomeScreen(AppScreen jf) {
        initComponents();
        title.setLocation(WIDTH, HEIGHT);
        title.setForeground(new Color(226,34,33));
        changePlayerButton.setLocation(WIDTH, HEIGHT);
        currentPlayerLabel.setText("Current Player:");
        currentPlayerLabel.setForeground(new Color(9,21,17));
        setPlayerName(Hanafuda.getPlayer().getName());
        currentPName.setForeground(new Color(9,21,17));
        nameBox.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(110,130,129)));
        nameBox.setText("Enter name here");
        nameBox.setVisible(false);
        newPButton.setVisible(false);
        newPButton.setBackground(new Color(233,185,234));
        returnButton.setVisible(false);
        newPlayerField.setText("Enter Name Here");
        newPlayerField.setVisible(false);
        parent = jf;
    }
    
    private void setPlayerName(String name) {
        currentPName.setText(name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HTPButton = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        playButton = new javax.swing.JButton();
        changePlayerButton = new javax.swing.JButton();
        currentPName = new javax.swing.JLabel();
        currentPlayerLabel = new javax.swing.JLabel();
        nameBox = new javax.swing.JTextField();
        newPButton = new javax.swing.JButton();
        returnButton = new javax.swing.JButton();
        newPlayerField = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(940, 950));

        HTPButton.setBackground(new java.awt.Color(255, 204, 255));
        HTPButton.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        HTPButton.setText("How to Play");
        HTPButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HTPButtonMouseClicked(evt);
            }
        });
        HTPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HTPButtonActionPerformed(evt);
            }
        });

        title.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 72)); // NOI18N
        title.setForeground(new java.awt.Color(255, 0, 0));
        title.setText("HANAFUDA");
        title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        playButton.setBackground(new java.awt.Color(255, 255, 255));
        playButton.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        playButton.setText("Play");
        playButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playButtonMouseClicked(evt);
            }
        });

        changePlayerButton.setBackground(new java.awt.Color(255, 153, 255));
        changePlayerButton.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        changePlayerButton.setText("Change Player");
        changePlayerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changePlayerButtonMouseClicked(evt);
            }
        });

        currentPName.setBackground(new java.awt.Color(0, 51, 51));
        currentPName.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        currentPName.setForeground(new java.awt.Color(255, 0, 0));
        currentPName.setText("[current player]");

        currentPlayerLabel.setBackground(new java.awt.Color(0, 51, 51));
        currentPlayerLabel.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        currentPlayerLabel.setForeground(new java.awt.Color(255, 0, 0));
        currentPlayerLabel.setText("Current Player:");

        nameBox.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        nameBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nameBox.setText("Enter Name Here");
        nameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameBoxActionPerformed(evt);
            }
        });
        nameBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameBoxKeyPressed(evt);
            }
        });

        newPButton.setBackground(new java.awt.Color(204, 204, 204));
        newPButton.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        newPButton.setText("New Player");
        newPButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newPButtonMouseClicked(evt);
            }
        });

        returnButton.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        returnButton.setText("Return");
        returnButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        newPlayerField.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        newPlayerField.setText("New Player Here");
        newPlayerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPlayerFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(title))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(359, 359, 359)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(currentPName))
                            .addComponent(currentPlayerLabel))))
                .addContainerGap(227, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(newPButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameBox)
                    .addComponent(changePlayerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HTPButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(playButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(returnButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newPlayerField))
                .addGap(376, 376, 376))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(currentPlayerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currentPName)
                .addGap(48, 48, 48)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 419, Short.MAX_VALUE)
                .addComponent(returnButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newPButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(playButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HTPButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(changePlayerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newPlayerField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void HTPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HTPButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HTPButtonActionPerformed

    private void changePlayerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePlayerButtonMouseClicked
        changePlayerButton.setVisible(false);
        nameBox.setVisible(true);
        newPButton.setVisible(true);
        returnButton.setVisible(true);
        title.setVisible(false);
        HTPButton.setVisible(false);
        playButton.setVisible(false);
        this.repaint();
    }//GEN-LAST:event_changePlayerButtonMouseClicked

    private void nameBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameBoxKeyPressed
        
    }//GEN-LAST:event_nameBoxKeyPressed

    private void nameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameBoxActionPerformed
        if (Hanafuda.setPlayer(nameBox.getText())) {
            nameBox.setVisible(false);
            newPButton.setVisible(false);
            returnButton.setVisible(false);
            title.setVisible(true);
            HTPButton.setVisible(true);
            playButton.setVisible(true);
            changePlayerButton.setVisible(true);
            currentPName.setText(Hanafuda.getPlayer().getName());
            nameBox.setText("Enter name here");
        } else {
            nameBox.setText("Invalid name");
        }
    }//GEN-LAST:event_nameBoxActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        nameBox.setVisible(false);
        newPButton.setVisible(false);
        returnButton.setVisible(false);
        title.setVisible(true);
        HTPButton.setVisible(true);
        playButton.setVisible(true);
        changePlayerButton.setVisible(true);
        newPlayerField.setVisible(false);
    }//GEN-LAST:event_returnButtonActionPerformed

    private void HTPButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HTPButtonMouseClicked
        parent.showScreen("htpH");
    }//GEN-LAST:event_HTPButtonMouseClicked

    private void newPButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newPButtonMouseClicked
        newPlayerField.setVisible(true);
        newPButton.setVisible(false);
        nameBox.setVisible(false);
        this.repaint();
    }//GEN-LAST:event_newPButtonMouseClicked

    private void newPlayerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPlayerFieldActionPerformed
        Player p = new Player(newPlayerField.getText());
        Hanafuda.playerList.add(p);
        Hanafuda.setPlayer(p.getName());
        currentPName.setText(p.getName());
        newPButton.setVisible(false);
        returnButton.setVisible(false);
        title.setVisible(true);
        HTPButton.setVisible(true);
        playButton.setVisible(true);
        changePlayerButton.setVisible(true);
        newPlayerField.setVisible(false);
        this.repaint();
    }//GEN-LAST:event_newPlayerFieldActionPerformed

    private void playButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playButtonMouseClicked
        HTPButton.setVisible(false);
        changePlayerButton.setVisible(false);
        currentPName.setVisible(false);
        currentPlayerLabel.setVisible(false);
        playButton.setVisible(false);
        title.setVisible(false);
        parent.showScreen("game");
    }//GEN-LAST:event_playButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HTPButton;
    private javax.swing.JButton changePlayerButton;
    private javax.swing.JLabel currentPName;
    private javax.swing.JLabel currentPlayerLabel;
    private javax.swing.JTextField nameBox;
    private javax.swing.JButton newPButton;
    private javax.swing.JTextField newPlayerField;
    private javax.swing.JButton playButton;
    private javax.swing.JButton returnButton;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
